package: yform_usability
version: '1.2.0'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/yform_usability
compile: 0

requires:
    packages:
        yform/manager: '^2.0'

page:

    hidden: true

pages:
    system/yform-usability:
        title: 'yform-usability'
    yform/manager/yform-usability:
        title: 'yform-usability'
