package: yform_usability
version: '1.3.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/yform_usability
compile: 0

requires:
    packages:
        yform/manager: '^2.0'

page:
    hidden: true

pages:
    yform/manager/usability:
        title: 'Usability'
    yform/manager/yform-usability:
        title: 'yform-usability'
        hidden: true

default_config:
    duplicate_tables: []
    status_tables: []
    sorting_tables: []
